// Seed dataset of REAL AI tools. Hardcoding this catalog is explicitly
// fine (per product spec) — what must never be hardcoded is the final
// recommendation OUTPUT, which is computed at request time by
// recommendationEngine.js against this data.
//
// Pricing/feature details are best-effort as of authoring time; products
// change plans often, so treat this as a seed to refresh periodically
// rather than a source of truth.

const tools = [
  // ---------- PDF / Research / Summarization ----------
  {
    name: "ChatPDF",
    description: "Upload a PDF and ask questions about it in plain language; returns cited answers and summaries.",
    category: "PDF & Research",
    capabilities: ["document summarization", "pdf summarization"],
    inputTypes: ["pdf"],
    outputTypes: ["text"],
    pricing: "Freemium",
    freeTier: true,
    apiAvailable: false,
    openSource: false,
    rating: 4.3,
    qualityScore: 78,
    tags: ["summarization", "pdf", "q&a"],
    officialWebsiteUrl: "https://www.chatpdf.com",
  },
  {
    name: "Scholarcy",
    description: "Turns academic papers and reports into structured summary flashcards with key findings highlighted.",
    category: "PDF & Research",
    capabilities: ["document summarization", "research summarization"],
    inputTypes: ["pdf"],
    outputTypes: ["text"],
    pricing: "Freemium",
    freeTier: true,
    apiAvailable: true,
    openSource: false,
    rating: 4.2,
    qualityScore: 80,
    tags: ["summarization", "academic", "research"],
    officialWebsiteUrl: "https://www.scholarcy.com",
  },
  {
    name: "SciSpace",
    description: "AI research assistant that explains, summarizes, and simplifies academic papers section by section.",
    category: "PDF & Research",
    capabilities: ["document summarization", "research summarization"],
    inputTypes: ["pdf"],
    outputTypes: ["text"],
    pricing: "Freemium",
    freeTier: true,
    apiAvailable: false,
    openSource: false,
    rating: 4.4,
    qualityScore: 82,
    tags: ["summarization", "academic", "research"],
    officialWebsiteUrl: "https://scispace.com",
  },
  {
    name: "Elicit",
    description: "AI research assistant that finds, summarizes, and extracts data from academic papers at scale.",
    category: "PDF & Research",
    capabilities: ["document summarization", "research summarization", "data analysis"],
    inputTypes: ["pdf", "text"],
    outputTypes: ["text"],
    pricing: "Freemium",
    freeTier: true,
    apiAvailable: false,
    openSource: false,
    rating: 4.5,
    qualityScore: 85,
    tags: ["research", "summarization"],
    officialWebsiteUrl: "https://elicit.com",
  },
  {
    name: "Humata",
    description: "Ask questions of long PDFs and get grounded, cited answers and summaries in seconds.",
    category: "PDF & Research",
    capabilities: ["document summarization", "pdf summarization"],
    inputTypes: ["pdf"],
    outputTypes: ["text"],
    pricing: "Freemium",
    freeTier: true,
    apiAvailable: true,
    openSource: false,
    rating: 4.1,
    qualityScore: 76,
    tags: ["summarization", "pdf"],
    officialWebsiteUrl: "https://www.humata.ai",
  },
  {
    name: "Consensus",
    description: "Search engine that answers questions using findings extracted directly from research papers.",
    category: "PDF & Research",
    capabilities: ["research summarization", "document summarization"],
    inputTypes: ["text"],
    outputTypes: ["text"],
    pricing: "Freemium",
    freeTier: true,
    apiAvailable: false,
    openSource: false,
    rating: 4.4,
    qualityScore: 83,
    tags: ["research", "summarization"],
    officialWebsiteUrl: "https://consensus.app",
  },

  // ---------- Writing / Script generation ----------
  {
    name: "Jasper",
    description: "AI writing platform for marketing copy, long-form content, and brand-consistent scripts.",
    category: "Writing",
    capabilities: ["script generation", "content generation"],
    inputTypes: ["text"],
    outputTypes: ["text"],
    pricing: "Paid",
    freeTier: false,
    apiAvailable: true,
    openSource: false,
    rating: 4.4,
    qualityScore: 84,
    tags: ["writing", "scriptwriting", "copywriting"],
    officialWebsiteUrl: "https://www.jasper.ai",
  },
  {
    name: "Copy.ai",
    description: "Generates marketing copy, outlines, and short scripts from a brief prompt or product description.",
    category: "Writing",
    capabilities: ["script generation", "content generation"],
    inputTypes: ["text"],
    outputTypes: ["text"],
    pricing: "Freemium",
    freeTier: true,
    apiAvailable: true,
    openSource: false,
    rating: 4.2,
    qualityScore: 78,
    tags: ["writing", "copywriting"],
    officialWebsiteUrl: "https://www.copy.ai",
  },
  {
    name: "Writesonic",
    description: "AI writer for articles, ad copy, and video/podcast scripts with tone and length controls.",
    category: "Writing",
    capabilities: ["script generation", "content generation"],
    inputTypes: ["text"],
    outputTypes: ["text"],
    pricing: "Freemium",
    freeTier: true,
    apiAvailable: true,
    openSource: false,
    rating: 4.1,
    qualityScore: 76,
    tags: ["writing", "scriptwriting"],
    officialWebsiteUrl: "https://writesonic.com",
  },
  {
    name: "Sudowrite",
    description: "AI writing partner built for fiction and narrative scripts, with tools to expand and rewrite scenes.",
    category: "Writing",
    capabilities: ["script generation", "content generation"],
    inputTypes: ["text"],
    outputTypes: ["text"],
    pricing: "Paid",
    freeTier: false,
    apiAvailable: false,
    openSource: false,
    rating: 4.3,
    qualityScore: 79,
    tags: ["writing", "creative", "scriptwriting"],
    officialWebsiteUrl: "https://www.sudowrite.com",
  },
  {
    name: "Grammarly",
    description: "Writing assistant that checks grammar, tone, and clarity, and can rewrite passages on request.",
    category: "Writing",
    capabilities: ["writing assistance", "content generation"],
    inputTypes: ["text"],
    outputTypes: ["text"],
    pricing: "Freemium",
    freeTier: true,
    apiAvailable: true,
    openSource: false,
    rating: 4.5,
    qualityScore: 88,
    tags: ["writing", "editing"],
    officialWebsiteUrl: "https://www.grammarly.com",
  },

  // ---------- Presentations ----------
  {
    name: "Gamma",
    description: "Generates full slide decks, documents, or webpages from a topic or outline in minutes.",
    category: "Presentations",
    capabilities: ["presentation generation", "slide generation"],
    inputTypes: ["text"],
    outputTypes: ["presentation"],
    pricing: "Freemium",
    freeTier: true,
    apiAvailable: false,
    openSource: false,
    rating: 4.6,
    qualityScore: 90,
    tags: ["presentation", "slides"],
    officialWebsiteUrl: "https://gamma.app",
  },
  {
    name: "Beautiful.ai",
    description: "Presentation software with AI-designed slide templates that auto-adjust as you add content.",
    category: "Presentations",
    capabilities: ["presentation generation", "slide generation"],
    inputTypes: ["text"],
    outputTypes: ["presentation"],
    pricing: "Freemium",
    freeTier: true,
    apiAvailable: false,
    openSource: false,
    rating: 4.3,
    qualityScore: 82,
    tags: ["presentation", "slides", "design"],
    officialWebsiteUrl: "https://www.beautiful.ai",
  },
  {
    name: "Tome",
    description: "AI-native storytelling and presentation tool that generates narrative decks from a short prompt.",
    category: "Presentations",
    capabilities: ["presentation generation", "slide generation"],
    inputTypes: ["text"],
    outputTypes: ["presentation"],
    pricing: "Freemium",
    freeTier: true,
    apiAvailable: false,
    openSource: false,
    rating: 4.2,
    qualityScore: 79,
    tags: ["presentation", "storytelling"],
    officialWebsiteUrl: "https://tome.app",
  },
  {
    name: "SlidesAI",
    description: "Google Slides add-on that converts blocks of text or outlines directly into formatted slides.",
    category: "Presentations",
    capabilities: ["presentation generation", "slide generation"],
    inputTypes: ["text"],
    outputTypes: ["presentation"],
    pricing: "Freemium",
    freeTier: true,
    apiAvailable: false,
    openSource: false,
    rating: 4.0,
    qualityScore: 74,
    tags: ["presentation", "slides"],
    officialWebsiteUrl: "https://www.slidesai.io",
  },

  // ---------- Image generation & editing ----------
  {
    name: "Midjourney",
    description: "High-quality AI image generator known for stylized, artistic output, accessed via Discord or web.",
    category: "Image Generation",
    capabilities: ["image generation", "text-to-image"],
    inputTypes: ["text"],
    outputTypes: ["image"],
    pricing: "Paid",
    freeTier: false,
    apiAvailable: false,
    openSource: false,
    rating: 4.7,
    qualityScore: 92,
    tags: ["image", "art", "logo generation"],
    officialWebsiteUrl: "https://www.midjourney.com",
  },
  {
    name: "DALL-E 3",
    description: "OpenAI's text-to-image model, integrated into ChatGPT, generates images from detailed prompts.",
    category: "Image Generation",
    capabilities: ["image generation", "text-to-image"],
    inputTypes: ["text"],
    outputTypes: ["image"],
    pricing: "Freemium",
    freeTier: true,
    apiAvailable: true,
    openSource: false,
    rating: 4.5,
    qualityScore: 88,
    tags: ["image", "art"],
    officialWebsiteUrl: "https://openai.com/index/dall-e-3",
  },
  {
    name: "Stable Diffusion",
    description: "Open-source text-to-image model that can be self-hosted or accessed through many front-ends.",
    category: "Image Generation",
    capabilities: ["image generation", "text-to-image"],
    inputTypes: ["text"],
    outputTypes: ["image"],
    pricing: "Open Source",
    freeTier: true,
    apiAvailable: true,
    openSource: true,
    rating: 4.4,
    qualityScore: 86,
    tags: ["image", "open source"],
    officialWebsiteUrl: "https://stability.ai",
  },
  {
    name: "Adobe Firefly",
    description: "Adobe's generative image model, built into Creative Cloud, tuned for commercially safe output.",
    category: "Image Generation",
    capabilities: ["image generation", "text-to-image"],
    inputTypes: ["text"],
    outputTypes: ["image"],
    pricing: "Freemium",
    freeTier: true,
    apiAvailable: true,
    openSource: false,
    rating: 4.3,
    qualityScore: 85,
    tags: ["image", "design"],
    officialWebsiteUrl: "https://www.adobe.com/products/firefly.html",
  },
  {
    name: "Leonardo AI",
    description: "Text-to-image generator with fine-tuned models for game assets, product shots, and logos.",
    category: "Image Generation",
    capabilities: ["image generation", "text-to-image", "logo generation"],
    inputTypes: ["text"],
    outputTypes: ["image"],
    pricing: "Freemium",
    freeTier: true,
    apiAvailable: true,
    openSource: false,
    rating: 4.4,
    qualityScore: 84,
    tags: ["image", "logo generation", "design"],
    officialWebsiteUrl: "https://leonardo.ai",
  },
  {
    name: "Ideogram",
    description: "AI image generator with strong text-rendering, popular for logos, posters, and typographic art.",
    category: "Image Generation",
    capabilities: ["image generation", "logo generation"],
    inputTypes: ["text"],
    outputTypes: ["image"],
    pricing: "Freemium",
    freeTier: true,
    apiAvailable: true,
    openSource: false,
    rating: 4.3,
    qualityScore: 82,
    tags: ["image", "logo generation", "typography"],
    officialWebsiteUrl: "https://ideogram.ai",
  },
  {
    name: "Photoroom",
    description: "AI photo editor for removing backgrounds, retouching, and generating product photography.",
    category: "Image Editing",
    capabilities: ["image editing"],
    inputTypes: ["image"],
    outputTypes: ["image"],
    pricing: "Freemium",
    freeTier: true,
    apiAvailable: true,
    openSource: false,
    rating: 4.5,
    qualityScore: 83,
    tags: ["image editing", "background removal"],
    officialWebsiteUrl: "https://www.photoroom.com",
  },
  {
    name: "Remove.bg",
    description: "One-click AI background remover for product photos and portraits.",
    category: "Image Editing",
    capabilities: ["image editing"],
    inputTypes: ["image"],
    outputTypes: ["image"],
    pricing: "Freemium",
    freeTier: true,
    apiAvailable: true,
    openSource: false,
    rating: 4.4,
    qualityScore: 80,
    tags: ["image editing", "background removal"],
    officialWebsiteUrl: "https://www.remove.bg",
  },

  // ---------- Video generation & editing ----------
  {
    name: "Runway",
    description: "AI video generation and editing suite, including text-to-video and video-to-video tools.",
    category: "Video Generation",
    capabilities: ["ai video generation", "video generation", "video editing"],
    inputTypes: ["text", "script", "image"],
    outputTypes: ["video"],
    pricing: "Freemium",
    freeTier: true,
    apiAvailable: true,
    openSource: false,
    rating: 4.4,
    qualityScore: 88,
    tags: ["video", "generative video"],
    officialWebsiteUrl: "https://runwayml.com",
  },
  {
    name: "Pika",
    description: "Text- and image-to-video generator focused on fast, stylized short clips.",
    category: "Video Generation",
    capabilities: ["ai video generation", "video generation"],
    inputTypes: ["text", "image"],
    outputTypes: ["video"],
    pricing: "Freemium",
    freeTier: true,
    apiAvailable: false,
    openSource: false,
    rating: 4.2,
    qualityScore: 80,
    tags: ["video", "generative video"],
    officialWebsiteUrl: "https://pika.art",
  },
  {
    name: "Synthesia",
    description: "Turns a script into a video with an AI presenter avatar and synced voiceover, no filming required.",
    category: "Video Generation",
    capabilities: ["ai video generation", "video generation"],
    inputTypes: ["script", "text"],
    outputTypes: ["video"],
    pricing: "Paid",
    freeTier: false,
    apiAvailable: true,
    openSource: false,
    rating: 4.5,
    qualityScore: 87,
    tags: ["video", "avatar", "explainer video"],
    officialWebsiteUrl: "https://www.synthesia.io",
  },
  {
    name: "HeyGen",
    description: "Generates avatar-presented videos from a script, with voice cloning and multi-language dubbing.",
    category: "Video Generation",
    capabilities: ["ai video generation", "video generation"],
    inputTypes: ["script", "text"],
    outputTypes: ["video"],
    pricing: "Freemium",
    freeTier: true,
    apiAvailable: true,
    openSource: false,
    rating: 4.5,
    qualityScore: 86,
    tags: ["video", "avatar", "dubbing"],
    officialWebsiteUrl: "https://www.heygen.com",
  },
  {
    name: "Pictory",
    description: "Converts long-form scripts, articles, or blog posts into short branded videos automatically.",
    category: "Video Generation",
    capabilities: ["ai video generation", "video generation"],
    inputTypes: ["script", "text"],
    outputTypes: ["video"],
    pricing: "Paid",
    freeTier: false,
    apiAvailable: false,
    openSource: false,
    rating: 4.1,
    qualityScore: 78,
    tags: ["video", "script-to-video"],
    officialWebsiteUrl: "https://pictory.ai",
  },
  {
    name: "InVideo",
    description: "AI video generation and editing platform with templates for educational and marketing videos.",
    category: "Video Generation",
    capabilities: ["ai video generation", "video generation", "video editing"],
    inputTypes: ["script", "text"],
    outputTypes: ["video"],
    pricing: "Freemium",
    freeTier: true,
    apiAvailable: false,
    openSource: false,
    rating: 4.2,
    qualityScore: 79,
    tags: ["video", "templates"],
    officialWebsiteUrl: "https://invideo.io",
  },
  {
    name: "Descript",
    description: "Edits video and audio by editing a text transcript; includes AI voice cloning and filler-word removal.",
    category: "Video Editing",
    capabilities: ["video editing", "audio editing"],
    inputTypes: ["video", "audio"],
    outputTypes: ["video", "audio"],
    pricing: "Freemium",
    freeTier: true,
    apiAvailable: false,
    openSource: false,
    rating: 4.6,
    qualityScore: 89,
    tags: ["video editing", "transcript editing"],
    officialWebsiteUrl: "https://www.descript.com",
  },
  {
    name: "CapCut",
    description: "Free video editor with AI-assisted captions, background removal, and templates for short-form video.",
    category: "Video Editing",
    capabilities: ["video editing"],
    inputTypes: ["video"],
    outputTypes: ["video"],
    pricing: "Freemium",
    freeTier: true,
    apiAvailable: false,
    openSource: false,
    rating: 4.5,
    qualityScore: 85,
    tags: ["video editing", "short-form"],
    officialWebsiteUrl: "https://www.capcut.com",
  },

  // ---------- Text to speech / speech to text ----------
  {
    name: "ElevenLabs",
    description: "High-fidelity text-to-speech and voice cloning with an API for building narration into apps.",
    category: "Text to Speech",
    capabilities: ["text to speech", "voice generation"],
    inputTypes: ["text", "script"],
    outputTypes: ["audio"],
    pricing: "Freemium",
    freeTier: true,
    apiAvailable: true,
    openSource: false,
    rating: 4.7,
    qualityScore: 93,
    tags: ["tts", "voice cloning", "narration"],
    officialWebsiteUrl: "https://elevenlabs.io",
  },
  {
    name: "Murf AI",
    description: "Studio for generating natural-sounding voiceovers from text, with pacing and emphasis controls.",
    category: "Text to Speech",
    capabilities: ["text to speech", "voice generation"],
    inputTypes: ["text", "script"],
    outputTypes: ["audio"],
    pricing: "Freemium",
    freeTier: true,
    apiAvailable: true,
    openSource: false,
    rating: 4.4,
    qualityScore: 84,
    tags: ["tts", "narration"],
    officialWebsiteUrl: "https://murf.ai",
  },
  {
    name: "PlayHT",
    description: "Text-to-speech API and studio with ultra-realistic voices and low-latency streaming for apps.",
    category: "Text to Speech",
    capabilities: ["text to speech", "voice generation"],
    inputTypes: ["text", "script"],
    outputTypes: ["audio"],
    pricing: "Freemium",
    freeTier: true,
    apiAvailable: true,
    openSource: false,
    rating: 4.3,
    qualityScore: 81,
    tags: ["tts", "api"],
    officialWebsiteUrl: "https://play.ht",
  },
  {
    name: "WellSaid Labs",
    description: "Enterprise-grade text-to-speech with a library of licensed studio-quality voice avatars.",
    category: "Text to Speech",
    capabilities: ["text to speech", "voice generation"],
    inputTypes: ["text", "script"],
    outputTypes: ["audio"],
    pricing: "Paid",
    freeTier: false,
    apiAvailable: true,
    openSource: false,
    rating: 4.2,
    qualityScore: 80,
    tags: ["tts", "enterprise"],
    officialWebsiteUrl: "https://wellsaidlabs.com",
  },
  {
    name: "OpenAI Whisper",
    description: "Open-source speech recognition model for transcription and translation, runs locally or via API.",
    category: "Speech to Text",
    capabilities: ["speech to text", "transcription"],
    inputTypes: ["audio"],
    outputTypes: ["text"],
    pricing: "Open Source",
    freeTier: true,
    apiAvailable: true,
    openSource: true,
    rating: 4.6,
    qualityScore: 90,
    tags: ["stt", "transcription", "open source"],
    officialWebsiteUrl: "https://github.com/openai/whisper",
  },
  {
    name: "Otter.ai",
    description: "Real-time meeting transcription with speaker labels, summaries, and searchable notes.",
    category: "Speech to Text",
    capabilities: ["speech to text", "transcription"],
    inputTypes: ["audio"],
    outputTypes: ["text"],
    pricing: "Freemium",
    freeTier: true,
    apiAvailable: false,
    openSource: false,
    rating: 4.4,
    qualityScore: 83,
    tags: ["stt", "meetings", "transcription"],
    officialWebsiteUrl: "https://otter.ai",
  },
  {
    name: "AssemblyAI",
    description: "Speech-to-text and audio intelligence API for transcription, summarization, and content moderation.",
    category: "Speech to Text",
    capabilities: ["speech to text", "transcription"],
    inputTypes: ["audio"],
    outputTypes: ["text"],
    pricing: "Freemium",
    freeTier: true,
    apiAvailable: true,
    openSource: false,
    rating: 4.5,
    qualityScore: 86,
    tags: ["stt", "api"],
    officialWebsiteUrl: "https://www.assemblyai.com",
  },

  // ---------- Music ----------
  {
    name: "Suno",
    description: "Generates full songs, including vocals and instrumentation, from a text description or lyrics.",
    category: "Music",
    capabilities: ["music generation"],
    inputTypes: ["text"],
    outputTypes: ["audio"],
    pricing: "Freemium",
    freeTier: true,
    apiAvailable: false,
    openSource: false,
    rating: 4.5,
    qualityScore: 85,
    tags: ["music", "songwriting"],
    officialWebsiteUrl: "https://suno.com",
  },
  {
    name: "Udio",
    description: "AI music generator that produces studio-quality songs across genres from a text prompt.",
    category: "Music",
    capabilities: ["music generation"],
    inputTypes: ["text"],
    outputTypes: ["audio"],
    pricing: "Freemium",
    freeTier: true,
    apiAvailable: false,
    openSource: false,
    rating: 4.3,
    qualityScore: 82,
    tags: ["music"],
    officialWebsiteUrl: "https://www.udio.com",
  },

  // ---------- Coding ----------
  {
    name: "GitHub Copilot",
    description: "AI pair programmer that suggests code completions and whole functions inside your editor.",
    category: "Coding",
    capabilities: ["code generation"],
    inputTypes: ["code", "text"],
    outputTypes: ["code"],
    pricing: "Freemium",
    freeTier: true,
    apiAvailable: true,
    openSource: false,
    rating: 4.5,
    qualityScore: 89,
    tags: ["coding", "pair programming"],
    officialWebsiteUrl: "https://github.com/features/copilot",
  },
  {
    name: "Cursor",
    description: "AI-native code editor built for large codebase edits, chat-driven refactors, and multi-file changes.",
    category: "Coding",
    capabilities: ["code generation"],
    inputTypes: ["code", "text"],
    outputTypes: ["code"],
    pricing: "Freemium",
    freeTier: true,
    apiAvailable: false,
    openSource: false,
    rating: 4.6,
    qualityScore: 90,
    tags: ["coding", "ide"],
    officialWebsiteUrl: "https://www.cursor.com",
  },

  // ---------- UI / Website generation ----------
  {
    name: "v0",
    description: "Generates React UI components and full pages from a text prompt or screenshot.",
    category: "UI Generation",
    capabilities: ["code generation", "website generation"],
    inputTypes: ["text", "image"],
    outputTypes: ["code"],
    pricing: "Freemium",
    freeTier: true,
    apiAvailable: false,
    openSource: false,
    rating: 4.4,
    qualityScore: 84,
    tags: ["ui generation", "frontend"],
    officialWebsiteUrl: "https://v0.dev",
  },
  {
    name: "Bolt.new",
    description: "Builds and deploys full-stack web apps from a natural-language prompt directly in the browser.",
    category: "Website Generation",
    capabilities: ["website generation", "code generation"],
    inputTypes: ["text"],
    outputTypes: ["code", "website"],
    pricing: "Freemium",
    freeTier: true,
    apiAvailable: false,
    openSource: false,
    rating: 4.3,
    qualityScore: 81,
    tags: ["website generation", "full-stack"],
    officialWebsiteUrl: "https://bolt.new",
  },
  {
    name: "Framer AI",
    description: "Generates and publishes a complete marketing website from a text prompt, with a visual editor.",
    category: "Website Generation",
    capabilities: ["website generation"],
    inputTypes: ["text"],
    outputTypes: ["website"],
    pricing: "Freemium",
    freeTier: true,
    apiAvailable: false,
    openSource: false,
    rating: 4.4,
    qualityScore: 83,
    tags: ["website generation", "design"],
    officialWebsiteUrl: "https://www.framer.com/ai",
  },
  {
    name: "Durable",
    description: "Generates a small-business website, copy, and logo in under a minute from a business description.",
    category: "Website Generation",
    capabilities: ["website generation", "logo generation"],
    inputTypes: ["text"],
    outputTypes: ["website"],
    pricing: "Freemium",
    freeTier: true,
    apiAvailable: false,
    openSource: false,
    rating: 4.0,
    qualityScore: 74,
    tags: ["website generation", "small business"],
    officialWebsiteUrl: "https://durable.co",
  },

  // ---------- Translation ----------
  {
    name: "DeepL",
    description: "Neural machine translation known for natural phrasing across dozens of languages, with an API.",
    category: "Translation",
    capabilities: ["translation"],
    inputTypes: ["text", "document"],
    outputTypes: ["text", "document"],
    pricing: "Freemium",
    freeTier: true,
    apiAvailable: true,
    openSource: false,
    rating: 4.6,
    qualityScore: 90,
    tags: ["translation"],
    officialWebsiteUrl: "https://www.deepl.com",
  },
  {
    name: "Google Translate",
    description: "Free translation across 100+ languages, with text, document, and camera translation.",
    category: "Translation",
    capabilities: ["translation"],
    inputTypes: ["text", "document", "image"],
    outputTypes: ["text"],
    pricing: "Freemium",
    freeTier: true,
    apiAvailable: true,
    openSource: false,
    rating: 4.5,
    qualityScore: 87,
    tags: ["translation"],
    officialWebsiteUrl: "https://translate.google.com",
  },

  // ---------- Education ----------
  {
    name: "Khanmigo",
    description: "Khan Academy's AI tutor that guides students through problems with Socratic questioning.",
    category: "Education",
    capabilities: ["tutoring", "education"],
    inputTypes: ["text"],
    outputTypes: ["text"],
    pricing: "Freemium",
    freeTier: true,
    apiAvailable: false,
    openSource: false,
    rating: 4.3,
    qualityScore: 82,
    tags: ["education", "tutoring"],
    officialWebsiteUrl: "https://www.khanacademy.org",
  },
  {
    name: "Duolingo Max",
    description: "Language-learning app with AI-powered conversation practice and mistake explanations.",
    category: "Education",
    capabilities: ["education", "translation"],
    inputTypes: ["text"],
    outputTypes: ["text"],
    pricing: "Freemium",
    freeTier: true,
    apiAvailable: false,
    openSource: false,
    rating: 4.4,
    qualityScore: 83,
    tags: ["education", "language learning"],
    officialWebsiteUrl: "https://www.duolingo.com",
  },

  // ---------- Data analysis ----------
  {
    name: "Julius AI",
    description: "Chat-based data analyst that writes and runs code to analyze spreadsheets and generate charts.",
    category: "Data Analysis",
    capabilities: ["data analysis"],
    inputTypes: ["csv", "spreadsheet"],
    outputTypes: ["chart", "text"],
    pricing: "Freemium",
    freeTier: true,
    apiAvailable: false,
    openSource: false,
    rating: 4.3,
    qualityScore: 80,
    tags: ["data analysis", "charts"],
    officialWebsiteUrl: "https://julius.ai",
  },
  {
    name: "Akkio",
    description: "No-code AI platform for building predictive models and analyzing business data automatically.",
    category: "Data Analysis",
    capabilities: ["data analysis"],
    inputTypes: ["csv", "spreadsheet"],
    outputTypes: ["chart", "text"],
    pricing: "Paid",
    freeTier: false,
    apiAvailable: true,
    openSource: false,
    rating: 4.1,
    qualityScore: 77,
    tags: ["data analysis", "predictive modeling"],
    officialWebsiteUrl: "https://www.akkio.com",
  },

  // ---------- Automation ----------
  {
    name: "Zapier",
    description: "Connects apps and automates workflows, with AI-generated automations ('Zaps') from plain language.",
    category: "Automation",
    capabilities: ["automation"],
    inputTypes: ["text"],
    outputTypes: ["workflow"],
    pricing: "Freemium",
    freeTier: true,
    apiAvailable: true,
    openSource: false,
    rating: 4.5,
    qualityScore: 87,
    tags: ["automation", "integrations"],
    officialWebsiteUrl: "https://zapier.com",
  },
  {
    name: "Make",
    description: "Visual automation builder for connecting apps and APIs into multi-step workflows.",
    category: "Automation",
    capabilities: ["automation"],
    inputTypes: ["text"],
    outputTypes: ["workflow"],
    pricing: "Freemium",
    freeTier: true,
    apiAvailable: true,
    openSource: false,
    rating: 4.4,
    qualityScore: 84,
    tags: ["automation", "integrations"],
    officialWebsiteUrl: "https://www.make.com",
  },
];

// Every catalog entry exposes a small, resilient logo source. ToolCard keeps
// an initials fallback in case a remote favicon cannot be reached.
export default tools.map((tool) => ({
  ...tool,
  logoUrl: tool.logoUrl || `https://www.google.com/s2/favicons?sz=64&domain_url=${encodeURIComponent(tool.officialWebsiteUrl)}`,
}));
